Backup/EasyUI.Liuy.UI/Controllers/SysRoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EasyUI.Liuy.Domain.Models;

namespace EasyUI.Liuy.UI.Controllers
{
    public class SysRoleController : Controller
    {
        private WorkOrderContext db = new WorkOrderContext();

        //
        // GET: /SysRole/

        public ActionResult Index()
        {
            return View(db.SysRoles.ToList());
             
        }

        //
        // GET: /SysRole/Details/5

        public ActionResult Details(int id = 0)
        {
            SysRole sysrole = db.SysRoles.Find(id);
            if (sysrole == null)
            {
                return HttpNotFound();
            }
            return View(sysrole);
        }

        //
        // GET: /SysRole/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /SysRole/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SysRole sysrole)
        {
            if (ModelState.IsValid)
            {
                db.SysRoles.Add(sysrole);
                db.SaveChanges();
                return Content("OK");
            }

            return View(sysrole);
        }

        //
        // GET: /SysRole/Edit/5

        public ActionResult Edit(int id = 0)
        {
            SysRole sysrole = db.SysRoles.Find(id);
            if (sysrole == null)
            {
                return HttpNotFound();
            }
            return View(sysrole);
        }

        //
        // POST: /SysRole/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SysRole sysrole)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sysrole).State = EntityState.Modified;
                db.SaveChanges();
                return Content("OK");
            }
            return View(sysrole);
        }

        //
        // GET: /SysRole/Delete/5

        public ActionResult Delete(int id = 0)
        {
            SysRole sysrole = db.SysRoles.Find(id);
            if (sysrole == null)
            {
                return HttpNotFound();
            }
            return View(sysrole);
        }

        //
        // POST: /SysRole/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SysRole sysrole = db.SysRoles.Find(id);
            db.SysRoles.Remove(sysrole);
            db.SaveChanges();
            return Content("OK");
        }

        public JsonResult GetRoleList()
        {
            var model = from s in
                            db.SysRoles.ToList()
                        select new
                            {
                                s.Id,
                                s.Name,
                                s.Description,
                                s.Type
                            };
            return Json(model, JsonRequestBehavior.AllowGet);
        }



        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Backup/EasyUI.Liuy.UI/Views/SysRole/Create.cshtml
@model EasyUI.Liuy.Domain.Models.SysRole

@{
    ViewBag.Title = "Create";
}
<script>
    function ff_submit() {
        $('#ff').form('submit', {
            success: function (data) {
                if (data == "OK") {
                    window.location.href = "/SysRole/Index";
                }
            }
        });
    }
</script>
 

@using (Html.BeginForm("Create", "SysRole", FormMethod.Post, new { id = "ff", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>创建角色</legend>

        <div class="editor-label">
             名称
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
           描述
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            类型
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Type)
            @Html.ValidationMessageFor(model => model.Type)
        </div>

         <input type="hidden" id="State" name="State" value="启用"/>

         <p>
                @Html.ActionLink("添加", null, null, new { onclick = "ff_submit()", iconcls = "icon-add", @class = "easyui-linkbutton", href = "javascript:void(0)" })

                @Html.ActionLink("返回", "Index", null, new { @class = "easyui-linkbutton", iconcls = "icon-back" })
            </p>
    </fieldset>
}
 

 

Backup/EasyUI.Liuy.UI/Views/SysRole/Delete.cshtml
@model EasyUI.Liuy.Domain.Models.SysRole

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>SysRole</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Type)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Type)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.State)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.State)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Backup/EasyUI.Liuy.UI/Views/SysRole/Details.cshtml
@model EasyUI.Liuy.Domain.Models.SysRole

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>SysRole</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Type)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Type)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.State)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.State)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Backup/EasyUI.Liuy.UI/Views/SysRole/Edit.cshtml
@model EasyUI.Liuy.Domain.Models.SysRole

@{
    ViewBag.Title = "Edit";
}

 
<script>
    function ff_submit() {
        $('#ff').form('submit', {
            success: function (data) {
                if (data == "OK") {
                    window.location.href = "/SysRole/Index";
                }
            }
        });
    }
</script>

@using (Html.BeginForm("Edit", "SysRole", FormMethod.Post, new { id = "ff", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>角色编辑</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
          名称
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
           描述
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
           类型
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Type)
            @Html.ValidationMessageFor(model => model.Type)
        </div>

        <div class="editor-label">
           状态
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.State)
            @Html.ValidationMessageFor(model => model.State)
        </div>

        <p>
            @Html.ActionLink("修改", null, null, new { onclick = "ff_submit()", iconcls="icon-ok", @class = "easyui-linkbutton", href = "javascript:void(0)" })

            @Html.ActionLink("返回", "Index",null,new{@class="easyui-linkbutton", iconcls="icon-back"})
        </p>
    </fieldset>
}
 
 

Backup/EasyUI.Liuy.UI/Views/SysRole/Index.cshtml
@model IEnumerable<EasyUI.Liuy.Domain.Models.SysRole>

@{
    ViewBag.Title = "Index";
}

<script>
    function ShowAddDialog() {
        window.location.href = "/SysRole/Create";

    }



    function ShowDeleteDialog() {

    }



    function ShowUpdateDialog() {
     
          window.location.href = "/SysRole/Edit/" + $("#dg").datagrid("getSelections")[0].Id;

    }


</script>
<div data-options="region:'north',title:'用户角色'" style="height: 100px;" border="false" fit="true">
    <table id="dg" class="easyui-datagrid" style="width: auto; height: auto" data-options="singleSelect:true,collapsible:true,pagination: true,
            rownumbers: true,
            pageSiz: 10,
            pageList: [10, 20, 30],     toolbar: [{ 
                text: '添加',
                iconCls: 'icon-add',
                handler: function () {
                    ShowAddDialog();
                }
            }, '-', { 
                text: '删除',
                iconCls: 'icon-remove',
                handler: function () {
                    ShowDeleteDialog();

                }
            }, '-', {
                text: '修改',
                iconCls: 'icon-edit',
                handler: function () {
                    ShowUpdateDialog();
                }
            }, '-']">
        <thead>
            <tr>
                 <th data-options="field:'Id',width:80">Id
                </th>
                <th data-options="field:'姓名',width:80">名称
                </th>
                <th data-options="field:'描述',width:80">描述
                </th>
                <th data-options="field:'类型',width:80">类型
                </th>
                <th data-options="field:'状态',width:80">状态
                </th>
                <th></th>
            </tr>
        </thead>


        @foreach (var item in Model)
        {
            <tr>
                  <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</div>