Backup/EasyUI.Liuy.UI/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using EasyUI.Liuy.Domain.Models;
using EasyUI.Liuy.Domain.Abstract.IService;
using EasyUI.Liuy.UI.ViewModels;

namespace EasyUI.Liuy.UI.Controllers
{

    public class WorkOrderController : Controller
    {
        private WorkOrderContext db = new WorkOrderContext();
        UploadInfoViewModel uploadInfo = new UploadInfoViewModel();

        private IWorkOrderService iWorkOrderService;
        private IReplyMessageService iReplyMessageService;
        // GET: /WorkOrder/
        public WorkOrderController(IWorkOrderService iService, IReplyMessageService iMessageService)
        {
            iWorkOrderService = iService;
            iReplyMessageService = iMessageService;
        }
        public ActionResult Index()
        {
            var workorders = db.WorkOrders.Include(w => w.Product);
            return View(workorders.ToList());
        }

        public JsonResult DataGrid(FormCollection form)
        {
            var user = Response.Cookies[".ASPXAUTH"].Value;
            var query = from s in iWorkOrderService.Search(c => true)
                        where
                       (string.IsNullOrEmpty(form["Id"]) ? true : s.Id == form["Id"]) &&
                     (string.IsNullOrEmpty(form["State"]) ? true : s.State.Contains(form["State"])) &&
                    (string.IsNullOrEmpty(form["Type"]) ? true : s.Type.Contains(form["Type"])) &&
                  (string.IsNullOrEmpty(form["Phone"]) ? true : s.Phone.Contains(form["Phone"])) &&
                  (string.IsNullOrEmpty(form["Service"]) ? true : s.Service.Contains(form["Service"])) &&
                        (string.IsNullOrEmpty(form["ProcessingMode"]) ? true : s.ProcessingMode.Contains(form["ProcessingMode"])) &&
                        (string.IsNullOrEmpty(form["ProductId"]) ? true : s.ProductId == int.Parse(form["ProductId"])) &&
                      (string.IsNullOrEmpty(form["Cstart"]) && string.IsNullOrEmpty(form["Cend"]) ? true : DateTime.Parse(s.CreateTime) >= DateTime.Parse(form["Cstart"]) && DateTime.Parse(s.CreateTime) <= DateTime.Parse(form["Cend"])) &&
                    (string.IsNullOrEmpty(form["Astart"]) && string.IsNullOrEmpty(form["Aend"]) ? true : DateTime.Parse(s.ProcessingTime) >= DateTime.Parse(form["Astart"]) && DateTime.Parse(s.ProcessingTime) <= DateTime.Parse(form["Aend"]))

                        select new
                        {
                            s.Id,
                            s.Type,
                            s.SIM,
                            s.Product.Name,
                            s.Terminal,
                            s.Service,
                            s.Quantity,
                            s.Company,
                            s.Contact,
                            s.Sex,
                            s.Phone,
                            s.ProblemDescription,
                            s.Attachment,
                            s.ProcessingMode,
                            s.SI,
                            s.Suggestion,
                            s.State
                        };

            return Json(query, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /WorkOrder/Details/5
        /// <summary>
        /// 待处理工单详细
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(string id, string type)
        {
            var query = iWorkOrderService.PendingById(id);
            var List = query.ReplyMessages.ToList();
            ViewBag.model = List;
            ViewBag.type = type == "1" ? "OK" : "";
            return View(query);
        }

        /// <summary>
        /// 受理工单阶梯性回复
        /// </summary>
        /// <returns></returns>
        public ActionResult Acceptance(HttpPostedFileBase Attachment)
        {
            //回复信息
            ReplyMessage replyMessage = new ReplyMessage();
            AccountInfo account = Session["account"] as AccountInfo;
            replyMessage.WorkOrderId = Request["Id"];
            replyMessage.Attachment = Request["hid-Attachment"];
            replyMessage.Suggestion = Request["Suggestion"];
            replyMessage.ProcessingMode = Request["ProcessingMode"];
            replyMessage.SI = Request["SI"];
            replyMessage.AcceptanceDep = account.Department;
            replyMessage.AcceptancePer = account.MyName;
            replyMessage.AcceptancePhone = account.TEL;
            replyMessage.CreateTime = Request["CreateTime"];
            replyMessage.ProcessingTime = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");

            if (Request["ProcessingMode"] == "直接归档")
            {
                //工单处理完成改变状态
                var model = iWorkOrderService.FindById(Request["Id"]);
                model.State = "完成";
                iWorkOrderService.Update(model);
                iReplyMessageService.AddAcceptance(replyMessage);
            }
            else
            {
                var model = iWorkOrderService.FindById(Request["Id"]);
                model.State = "待处理";
                model.ProcessingMode = "转相关SI";
                iWorkOrderService.Update(model);
                iReplyMessageService.AddAcceptance(replyMessage);
            }

            //上传文件
            uploadInfo.IsReady = false;


            if (!string.IsNullOrEmpty(Request["hid-Attachment"]))
            {

                string path = this.Server.MapPath(@"../Uploads");
                string fileName = Path.GetFileName(Attachment.FileName);

                uploadInfo.ContentLength = Attachment.ContentLength;
                uploadInfo.FileName = fileName;
                uploadInfo.UploadedLength = 0;

                uploadInfo.IsReady = true;

                int bufferSize = 1;
                byte[] buffer = new byte[bufferSize];



                using (FileStream fs = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    while (uploadInfo.UploadedLength < uploadInfo.ContentLength)
                    {
                        int bytes = Attachment.InputStream.Read(buffer, 0, bufferSize);
                        fs.Write(buffer, 0, bytes);
                        uploadInfo.UploadedLength += bytes;
                    }
                }
            }
            return Content("OK");

        }

        /// <summary>
        /// 工单查询
        /// </summary>
        /// <returns></returns>
        public ActionResult Query()
        {
            var model = iWorkOrderService.Search(c => c.State == "待处理");
            return View(model);
        }

        //
        // GET: /WorkOrder/Create

        public ActionResult Create()
        {
            ViewBag.ProductId = new SelectList(db.Products, "Id", "Name");
            ViewBag.Id = DateTime.Now.ToString("yyMMddHHmms");
            return View();
        }

        //
        // POST: /WorkOrder/Create

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase Attachment)
        {
            WorkOrder workOrder = new WorkOrder();


            workOrder.Id = Request["Id"];
            workOrder.Type = Request["Type"];
            workOrder.SIM = Request["SIM"];
            workOrder.ProductId = int.Parse(Request["ProductId"]);
            workOrder.Terminal = Request["Terminal"];
            workOrder.Service = Request["Service"];
            workOrder.Quantity = int.Parse(Request["Quantity"]);
            workOrder.Company = Request["Company"];
            workOrder.Contact = Request["Contact"];
            workOrder.Sex = Request["Sex"];
            workOrder.Phone = Request["Phone"];
            workOrder.ProblemDescription = Request["ProblemDescription"];
            workOrder.Attachment = Request["hid-Attachment"];
            workOrder.ProcessingMode = Request["ProcessingMode"];
            workOrder.SI = Request["SI"];
            workOrder.Suggestion = Request["Suggestion"];
            workOrder.State = Request["State"];

            workOrder.CreateTime = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");

            iWorkOrderService.Add(workOrder);


            #region MyRegion
            //if (Filedata == null ||
            //        string.IsNullOrEmpty(Filedata.FileName) ||
            //        Filedata.ContentLength == 0)
            //{
            //    return this.HttpNotFound();
            //}

            //// 保存到 ~/photos 文件夹中，名称不变
            //string filename = System.IO.Path.GetFileName(Filedata.FileName);
            //string virtualPath =
            //    string.Format("UploadFile/{0}", filename);
            //// 文件系统不能使用虚拟路径
            //string path = this.Server.MapPath(virtualPath);

            //Filedata.SaveAs(path); 
            #endregion


            uploadInfo.IsReady = false;


            #region MyRegion
            if (!string.IsNullOrEmpty(Request["hid-Attachment"]))
            {

                string path = this.Server.MapPath(@"../Uploads");
                string fileName = Path.GetFileName(Attachment.FileName);

                uploadInfo.ContentLength = Attachment.ContentLength;
                uploadInfo.FileName = fileName;
                uploadInfo.UploadedLength = 0;

                uploadInfo.IsReady = true;

                int bufferSize = 1;
                byte[] buffer = new byte[bufferSize];



                using (FileStream fs = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    while (uploadInfo.UploadedLength < uploadInfo.ContentLength)
                    {
                        int bytes = Attachment.InputStream.Read(buffer, 0, bufferSize);
                        fs.Write(buffer, 0, bytes);

Backup/EasyUI.Liuy.UI/Views/WorkOrder/Create.cshtml
@model EasyUI.Liuy.Domain.Models.WorkOrder

@{
    ViewBag.Title = "Create";
    //  Layout = null;
}
<link href="~/Scripts/uploadify/uploadify.css" rel="stylesheet" />

<script src="~/Scripts/uploadify/jquery.uploadify.min.js"></script>

<script>

    function submitForm() {

        $('#ff').form('submit', {
            success: function (data) {
                $('#ff').form('clear');

                $.messager.show({
                    title: '成功',
                    msg: data + '工单信息添加成功',
                    showType: 'fade',
                    interval: 5000,
                    style: {
                        right: '',
                        top: document.body.scrollTop + document.documentElement.scrollTop,
                        bottom: ''
                    }
                });
                var d = new Date();
                var vYear = d.getFullYear();
                var vMon = d.getMonth() + 1;
                var vDay = d.getDate();
                var h = d.getHours();
                var m = d.getMinutes();
                var se = d.getSeconds();
                var s = vYear + (vMon < 10 ? "0" + vMon : vMon) + (vDay < 10 ? "0" + vDay : vDay) + (h < 10 ? "0" + h : h) + (m < 10 ? "0" + m : m) + (se < 10 ? "0" + se : se);
                //生成本地时间赋值给ID
                $("#Id").val(s);
                $("#hid").val(s);

            }
        });

    }
    function clearForm() {
        window.location.reload();
    }


    $(function () {
        //隐藏Si
        $("#obj").css("display", "none");
        $("#objselect").css("display", "none");
        //处理方式
        $('#ProcessingMode').combobox({
            onChange: function () {
                if ($('#ProcessingMode').combobox("getValue") == "转相关SI") {
                    $("#obj").fadeIn("slow");
                    $("#objselect").fadeIn("slow");
                    $("#State").val("待处理");
                } else {
                    $("#obj").fadeOut("slow");
                    $("#objselect").fadeOut("slow");
                    $("#State").val("完成");
                }
            }
        });
        //附件值
        $("#Attachment").change(function () {

            var att = $("#Attachment").val();
            $("#hid-Attachment").val(att.substring(12, att.length));
           
        });


    });

</script>



@using (Html.BeginForm("Create", "WorkOrder", FormMethod.Post, new { id = "ff", enctype = "multipart/form-data" }))
{
    <div class="easyui-panel" title="新建工单" style="width: auto;">

        <div style="padding: 10px 0 10px 100px;">

            <table>
                <tr>
                    <td>工单号:</td>
                    <td>
                        <input type="hidden" id="hid" name="hid" />
                        <input style="width:130px;"    class="easyui-validatebox" type="text" name="Id"  value ="@ViewBag.Id" id="Id" />
                    </td>
                    <td>工单类型:</td>
                    <td>
                        <select class="easyui-combobox" name="Type" id="Type" @*data-options="required:true,editable:false" *@style="width: 130px;">
                            <option value=""></option>
                            <option value="客户投诉">客户投诉</option>
                            <option value="故障处理">故障处理</option>
                            <option value="工作调度">工作调度</option>
                            <option value="优化需求">优化需求</option>
                            <option value="业务开通">业务开通</option>
                            <option value="终端申请">终端申请</option>
                        </select>
                    </td>
                </tr>

                <tr>

                    <input type="hidden" id="State" name="State" value="完成" />
                    <td>SIM卡号:</td>
                    <td>
                        <input style="width: 130px;" class="easyui-validatebox" type="text" name="SIM" /></td>
                </tr>

                <tr>
                    <td>相关产品:</td>
                    <td>
                        <select style="width: 130px;" class="easyui-combobox" name="ProductId" id="ProductId" data-options="required:true,editable:false">
                            <option value=""></option>
                            <option value="1">摩托车防盗器</option>
                            <option value="2">电动车防盗器</option>
                            <option value="3">汽车防盗器</option>
                        </select>
                    </td>
                    <td>终端编号:</td>
                    <td>
                        <input style="width: 130px;" class="easyui-validatebox" type="text" name="Terminal" data-options="required:false" /></td>

                </tr>
                <tr>
                    <td>服务类型:</td>
                    <td>
                        <select style="width: 130px;" class="easyui-combobox" name="Service" data-options="required:true,editable:false">
                            <option value=""></option>
                            <option value="终端类">终端类</option>
                            <option value="费用类">费用类</option>
                            <option value="其他">其他</option>
                        </select>
                    </td>
                    <td>终端数量:</td>
                    <td>
                        <input style="width: 130px;" class="easyui-validatebox" type="text" name="Quantity" data-options="required:true" maxlength="2"></input></td>

                </tr>
                <tr>
                    <td>客户名称:</td>
                    <td>
                        <input style="width: 130px;" class="easyui-validatebox" type="text" name="Company" data-options="required:true" /></td>

                    <td>联系人:</td>
                    <td>
                        <input style="width: 130px;" class="easyui-validatebox" type="text" name="Contact" data-options="required:true" /></td>
                </tr>
                <tr>
                    <td>性别:</td>
                    <td>
                        <select class="easyui-combobox" name="Sex">
                            <option value="男">男</option>
                            <option value="女">女</option>
                        </select>
                    </td>
                    <td>联系电话:</td>
                    <td>
                        <input style="width: 130px;" class="easyui-validatebox" type="text" name="Phone" @*data-options="required:true"*@/></td>
                </tr>
                <tr>
                    <td>问题描述:</td>
                    <td colspan="3">
                        <textarea name="ProblemDescription" style="height: 60px; width: 410px"></textarea></td>
                </tr>
                <tr>
                    <td>相关附件:</td>
                    <td colspan="3">
                        <input type="file" name="Attachment" id="Attachment" />
                        <input type="hidden" name="hid-Attachment" id="hid-Attachment" />
                    </td>
                </tr>
                <tr>
                    <td>处理方式:</td>
                    <td>
                        <select style="width: 130px;" class="easyui-combobox" name="ProcessingMode" id="ProcessingMode" data-options="required:true,editable:false">
                            <option value=""></option>
                            <option value="直接归档">直接归档</option>
                            <option value="转相关SI">转相关SI</option>
                        </select>
                    </td>

                    <td id="obj">转交对象:</td>
                    <td id="objselect">
                        <select style="width: 130px;" class="easyui-combobox" name="SI" @*data-options="required:true,editable:false"*@>
                            <option value=""></option>
                            <option value="重庆君翰科技有限公司">重庆君翰科技有限公司</option>
                            <option value="上海捷波">上海捷波</option>
                        </select>
                    </td>


                </tr>
                <tr>
                    <td>处理意见:</td>
                    <td colspan="3">
                        <textarea name="Suggestion" style="height: 60px; width: 410px"></textarea></td>
                </tr>

            </table>

        </div>





        <span id="uploadify"></span>
        <div style="text-align: center; padding: 5px 220px 10px 10px">

            <a href="javascript:void(0)" class="easyui-linkbutton" onclick="clearForm()">清除</a>
            <a href="javascript:void(0)" class="easyui-linkbutton" onclick="submitForm()" id="submit">确定</a>
        </div>
    </div>     
}

Backup/EasyUI.Liuy.UI/Views/WorkOrder/Delete.cshtml
@model EasyUI.Liuy.Domain.Models.WorkOrder

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>WorkOrder</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Type)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Type)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Product.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Product.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Quantity)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quantity)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Contact)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Contact)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Sex)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sex)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProblemDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProblemDescription)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProcessingMode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProcessingMode)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Suggestion)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Suggestion)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SI)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SI)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Attachment)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Attachment)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SIM)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SIM)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Terminal)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Terminal)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Company)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Company)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.State)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.State)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreateTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreateTime)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProcessingTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProcessingTime)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Backup/EasyUI.Liuy.UI/Views/WorkOrder/Details.cshtml
@using EasyUI.Liuy.Domain.Models
@model EasyUI.Liuy.Domain.Models.WorkOrder

@{
    ViewBag.Title = "Details";
}
<style>
    .tb tr { height: 25px; text-align: center; }

    .striped { background-color: #F1F1F1; }
</style>
<script>
    $(function () {
        $("#form1 table tr td:nth-child(odd)").css("color", "#3B7EC3");
        $("#form1  table tr:nth-child(even)").addClass("striped");
        //隐藏受理
        $("#sl-div2").css("display", "none");
        //隐藏Si
        $("#obj").css("display", "none");
        $("#objselect").css("display", "none");

        $("#ProcessingMode").combobox({
            onSelect: function () {
                var model = $("#ProcessingMode").combobox("getValue");
                if (model == "转相关SI") {
                    $("#obj").fadeIn("slow");
                    $("#objselect").fadeIn("slow");
                } else {
                    $("#obj").fadeOut("slow");
                    $("#objselect").fadeOut("slow");
                }
            }
        });

        $("#sl-btn").click(function () {

            $("#CreateTime").val(CurentTime);
            $("#sl-div2").slideDown("slow");
            $("#sl-div1").css("display", "none");
            $("#Attachment").change(function () {
                var att = $("#Attachment").val();
                $("#hid-Attachment").val(att.substring(12, att.length));

            });
        });
    });
    //受理时间
    function CurentTime() {
        var now = new Date();

        var year = now.getFullYear();
        var month = now.getMonth() + 1;
        var day = now.getDate();

        var hh = now.getHours();
        var mm = now.getMinutes();
        var se = now.getSeconds();

        var s = year + "-" + (month < 10 ? "0" + month : month) + "-" + (day < 10 ? "0" + day : day) + " " + (hh < 10 ? "0" + hh : hh) + ":" + (mm < 10 ? "0" + mm : mm) + ":" + (se < 10 ? "0" + se : se);

        return (s);
    }
    function submitForm() {
        $('#ff').form('submit', {
            success: function (data) {
                if (data == "OK") {
                    window.location.href = "/WorkOrder/Pending";
                }
            }
        });
    }
</script>
<div data-options="region:'north',title:'工单详细信息'" style="height: 100px;" border="false" fit="true">
    <form id="form1">
        <table cellpadding="0" cellspacing="0" style="width: 100%; table-layout: fixed;" class="tb">

            <tr>
                <td style="color: #0099FF;" colspan="4">
                    <h3>工单详细信息</h3>
                </td>
            </tr>
            <tr>
                <td>工单号</td>
                <td>@Model.Id</td>
                <td>工单类型</td>
                <td>@Model.Type</td>
            </tr>
            <tr>
                <td>相关SI</td>
                <td>@Model.SI</td>
                <td>相关产品</td>
                <td>@Model.Product.Name</td>

            </tr>
            <tr>
                <td>SIM卡号</td>
                <td>@Model.SIM</td>
                <td>终端编号</td>
                <td>@Model.Terminal</td>
            </tr>
            <tr>
                <td>建单时间</td>
                <td>@Model.CreateTime</td>
                <td>处理时间</td>
                <td>@Model.ProcessingTime</td>
            </tr>
            <tr>
                <td>相关终端数量</td>
                <td>@Model.Quantity</td>
                <td>问题描述</td>
                <td>@Model.ProblemDescription</td>

            </tr>
            <tr>
                <td>状态</td>
                <td style="color: green">@Model.State</td>
            </tr>
            <tr>
                <td style="color: #0099FF;" colspan="4">
                    <h3>客户详细信息</h3>
                </td>

            </tr>
            <tr>
                <td>客户 名称</td>
                <td>@Model.Company</td>
                <td>联系人</td>
                <td>@Model.Contact</td>
            </tr>
            <tr>
                <td>性别</td>
                <td>@Model.Sex</td>
                <td>联系电话</td>
                <td>@Model.Phone</td>
            </tr>
        </table>

    </form>
    <div style="text-align: center; padding: 10px; background-color: #FFFFFF">
        <h3 style="color: #0099FF;">回复信息</h3>
    </div>

    <form id="form2">
        <table id="dg" class="easyui-datagrid" style="width: auto; height: auto;" data-options="singleSelect:true,collapsible:true,fitColumns: true">
            <thead>
                <tr>
                    <th data-options="field:'Id',width:80,align:'center'">序号</th>
                    <th data-options="field:'AcceptanceDep',width:80,align:'center'">受理单位</th>
                    <th data-options="field:'AcceptancePhone',width:80,align:'center'">联系电话</th>
                    <th data-options="field:'ProcessingMode',width:80,align:'center'">处理方式</th>
                    <th data-options="field:'SI',width:80,align:'center'">转交对象</th>
                    <th data-options="field:'CreateTime',width:80,align:'center'">受理时间</th>
                    <th data-options="field:'ProcessingTime',width:80,align:'center'">处理时间</th>
                    <th data-options="field:'Suggestion',width:80,align:'center'">意见</th>
                    <th data-options="field:'Attachment',width:80,align:'center'">附件</th>

                </tr>
            </thead>

            @foreach (ReplyMessage s in ViewBag.model)
            {
                <tr>
                    <td>@s.Id</td>
                    <td>@s.AcceptanceDep</td>
                    <td>@s.AcceptancePhone</td>
                    <td>@s.ProcessingMode</td>
                    <td>@s.SI</td>
                    <td>@s.CreateTime</td>
                    <td>@s.ProcessingTime</td>
                    <td>@s.Suggestion</td>
                    <td><a href="/Uploads/@s.Attachment">@s.Attachment</a></td>
                </tr>
            }

        </table>
    </form>
    <div style="text-align: center; padding: 10px; background-color: #D3DFEB">
        <div id="sl-div2">

            @using (Html.BeginForm("Acceptance", "WorkOrder", FormMethod.Post, new { id = "ff", enctype = "multipart/form-data" }))
            {
                <input type="hidden" name="Id"  value="@Model.Id"/>
                <input type="hidden" id="CreateTime" name="CreateTime" />
                <div class="easyui-panel" title="受理工单" style="width: auto;">
                    <div style="padding: 10px 0 10px 400px">
                        <table style="text-align: center;">
                            <tr>
                                <td>处理意见:</td>
                                <td colspan="3">
                                    <textarea class="easyui-validatebox" data-options="required:true" name="Suggestion" style="height: 60px; width: 410px"></textarea></td>
                            </tr>
                            <tr>
                                <td>上传附件:</td>
                                <td colspan="3">
                                    <input type="file" name="Attachment" id="Attachment" />
                                    <input type="hidden" name="hid-Attachment" id="hid-Attachment" />
                                </td>
                            </tr>
                            <tr>
                                <td>处理方式:</td>
                                <td>
                                    <select class="easyui-combobox" name="ProcessingMode" id="ProcessingMode">
                                        <option value="直接归档">直接归档</option>
                                        <option value="转相关SI">转相关SI</option>
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <td id="obj">提醒对象:</td>
                                <td id="objselect">
                                    <select class="easyui-combobox" name="SI" id="SI">
                                        <option value="重庆君翰科技有限公司">重庆君翰科技有限公司</option>
                                        <option value="上海捷波">上海捷波</option>
                                    </select>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div style="text-align: center; padding: 5px 220px 10px 250px">

                        <a href="javascript:void(0)" class="easyui-linkbutton" onclick="window.history.go(-1)">返回</a>
                        <a href="javascript:void(0)" class="easyui-linkbutton" onclick="submitForm()" id="submit">提交处理</a>
                        @*                        <input type="submit" value="提交" />*@
                        @*                        <a href="javascript:void(0)" class="easyui-linkbutton" onclick="javascript:window.location.href = '/WorkOrder/Acceptance/@Model.Id'">阶梯性回复</a>*@
                    </div>
                </div>
            }
        </div>
        <div id="sl-div1">
            <a href="javascript:void(0)" class="easyui-linkbutton" onclick="window.location.href='/WorkOrder/Pending'">返回</a>
            @if (ViewBag.type == "OK")
            {
                <a href="javascript:void(0)" class="easyui-linkbutton" onclick="" id="sl-btn">追回工单</a>
            }
            else
            {
                <a href="javascript:void(0)" class="easyui-linkbutton" onclick="" id="sl-btn">受理</a>
            }
        </div>


    </div>
</div>