Backup/EasyUI.Liuy.UI/Controllers/SysDepartmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EasyUI.Liuy.Domain.Models;

namespace EasyUI.Liuy.UI.Controllers
{
    public class SysDepartmentController : Controller
    {
        private WorkOrderContext db = new WorkOrderContext();

        //
        // GET: /SysDepartment/

        public ActionResult Index()
        {
            return View(db.SysDepartments.ToList());
        }

        public JsonResult DataGrid()
        {
            var model = from s in db.SysDepartments
                        select new
                        {
                            s.Id,
                            s.Name,
                            Parent = s.SysDepartment2.Name,
                            s.Sort,
                            s.State
                        };
            return Json(model);
        }
        //
        // GET: /SysDepartment/Details/5

        public ActionResult Details(int id = 0)
        {
            SysDepartment sysdepartment = db.SysDepartments.Find(id);
            if (sysdepartment == null)
            {
                return HttpNotFound();
            }
            return View(sysdepartment);
        }

        //
        // GET: /SysDepartment/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /SysDepartment/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SysDepartment sysdepartment)
        {
            if (ModelState.IsValid)
            {
                db.SysDepartments.Add(sysdepartment);
                db.SaveChanges();
                return Content("OK");
            }

            return View(sysdepartment);
        }

        //
        // GET: /SysDepartment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            SysDepartment sysdepartment = db.SysDepartments.Find(id);
            if (sysdepartment == null)
            {
                return HttpNotFound();
            }
            return View(sysdepartment);
        }

        //
        // POST: /SysDepartment/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SysDepartment sysdepartment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sysdepartment).State = EntityState.Modified;
                db.SaveChanges();
                return Content("OK");
            }
            return View(sysdepartment);
        }

        //
        // GET: /SysDepartment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            SysDepartment sysdepartment = db.SysDepartments.Find(id);
            if (sysdepartment == null)
            {
                return HttpNotFound();
            }
            return View(sysdepartment);
        }

        //
        // POST: /SysDepartment/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SysDepartment sysdepartment = db.SysDepartments.Find(id);
            db.SysDepartments.Remove(sysdepartment);
            db.SaveChanges();
            return Content("OK");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Backup/EasyUI.Liuy.UI/Views/SysDepartment/Create.cshtml
@model EasyUI.Liuy.Domain.Models.SysDepartment 
@{
    ViewBag.Title = "Create";
}
<script>
    function ff_submit() {
        $('#ff').form('submit', {
            success: function (data) {
                if (data == "OK") {
                    window.location.href = "/SysDepartment/Index";
                }
            }
        });
    }
</script>
 

@using (Html.BeginForm("Create", "SysDepartment", FormMethod.Post, new { id = "ff", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="easyui-panel" title="创建部门">
        <fieldset>
            <legend>部门</legend>

            <div class="editor-label">
               部门名称
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
              
            </div>

            <div class="editor-label">
            夫栏目ID
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ParentId)
                 
            </div>

            <div class="editor-label">
                排序
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Sort)
               
            </div>

            <div class="editor-label">
              状态
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.State)
                
            </div>

            <p>
                @Html.ActionLink("添加", null, null, new { onclick = "ff_submit()", iconcls = "icon-add", @class = "easyui-linkbutton", href = "javascript:void(0)" })

                @Html.ActionLink("返回", "Index", null, new { @class = "easyui-linkbutton", iconcls = "icon-back" })
            </p>
        </fieldset>
    </div>
}

Backup/EasyUI.Liuy.UI/Views/SysDepartment/Delete.cshtml
@model EasyUI.Liuy.Domain.Models.SysDepartment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>SysDepartment</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ParentId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ParentId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Sort)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sort)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.State)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.State)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Backup/EasyUI.Liuy.UI/Views/SysDepartment/Details.cshtml
@model EasyUI.Liuy.Domain.Models.SysDepartment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>SysDepartment</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ParentId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ParentId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Sort)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sort)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.State)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.State)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Backup/EasyUI.Liuy.UI/Views/SysDepartment/Edit.cshtml
@model EasyUI.Liuy.Domain.Models.SysDepartment

@{
    ViewBag.Title = "Edit";
}
 
<script>
    function ff_submit() {
        $('#ff').form('submit', {
            success: function (data) {
                if (data == "OK") {
                    window.location.href = "/SysDepartment/Index";
                }
            }
        });
    }
</script>

@using (Html.BeginForm("Edit", "SysDepartment", FormMethod.Post, new { id = "ff", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>部门编辑</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            部门名称
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
           上级部门
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ParentId)
            @Html.ValidationMessageFor(model => model.ParentId)
        </div>

        <div class="editor-label">
           排序
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Sort)
            @Html.ValidationMessageFor(model => model.Sort)
        </div>

        <div class="editor-label">
          状态
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.State)
            @Html.ValidationMessageFor(model => model.State)
        </div>

        <p>
            @Html.ActionLink("修改", null, null, new { onclick = "ff_submit()", iconcls="icon-ok", @class = "easyui-linkbutton", href = "javascript:void(0)" })

            @Html.ActionLink("返回", "Index",null,new{@class="easyui-linkbutton", iconcls="icon-back"})
        </p>
    </fieldset>
}

 

 

Backup/EasyUI.Liuy.UI/Views/SysDepartment/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<script>
    $(function () {
        $("#dg").datagrid({
            url: "../SysDepartment/DataGrid",
            //title: "数据",
            iconCls: "icon-add",
            singleSelect: false,
            fitColumns: false,
            idField: "id",
            loadMsg: "正在加载数据",
            pagination: true,
            rownumbers: true,
            pageSiz: 10,
            pageList: [10, 20, 30],
            sortName: "Name",
            sortOrder: "asc",
            columns: [[
                { field: 'ck', checkbox: true },
                { field: 'Id', title: '编号', width: 100 },
                { field: 'Name', title: '部门名称', width: 100, sortable: true },//sortable:true点击该列的时候可以改变升降序
                { field: 'Parent', title: '上级部门', width: 100 },
                { field: 'Sort', title: '排序', width: 100 },
                { field: 'State', title: '状态', width: 100 }]],
            toolbar: [{//在dategrid表单的头部添加按钮
                text: "添加",
                iconCls: "icon-add",
                handler: function () {
                    ShowAddDialog();
                }
            }, '-', {//'-'就是在两个按钮的中间加一个竖线分割，看着舒服
                text: "删除",
                iconCls: "icon-remove",
                handler: function () {
                    ShowDeleteDialog();

                }
            }, '-', {
                text: "修改",
                iconCls: "icon-edit",
                handler: function () {
                    ShowUpdateDialog();
                }
            }, '-']

        });
    });
    function ShowUpdateDialog() {
        window.location.href = "/SysDepartment/Edit/" + $("#dg").datagrid("getSelections")[0].Id;
    }

    function ShowAddDialog() {
        window.location.href = "/SysDepartment/Create";
    }
</script>
<div data-options="region:'center',split:false,title:'用户角色'">
    <table id="dg">
    </table>
</div>